name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Run pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run pylint only in selected folders
        run: |
          pylint $(git ls-files 'archival-pipeline/*.py' 'scraper-pipeline/*.py')
