name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Run pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Homebrew
        run: |
          if ! command -v brew &> /dev/null; then
            echo "Homebrew not found, installing..."
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          else
            echo "Homebrew is already installed."
          fi

      - name: Install Cairo dependencies (macOS)
        run: |
          brew install cairo

      - name: Set environment variable for macOS
        run: |
          echo "DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib:$DYLD_FALLBACK_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r scraper-pipeline/requirements.txt
          pip install -r archival-pipeline/requirements.txt
          pip install -r dashboard/requirements.txt
          pip install -r daily-report/requirements.txt

      - name: Run pylint
        run: |
          pylint scraper-pipeline/*.py --fail-under=9.5
          pylint archival-pipeline/*.py --fail-under=9.5
